# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{jquery-mobile-rails}
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Matthew J. Bellantoni"]
  s.date = %q{2011-08-21}
  s.description = %q{ }
  s.email = %q{mjbellantoni@yahoo.com}
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "README.md",
    "Rakefile",
    "VERSION",
    "jquery-mobile-rails.gemspec",
    "lib/jquery-mobile-rails.rb",
    "lib/jquery-mobile/rails.rb",
    "lib/jquery-mobile/rails/engine.rb",
    "lib/jquery-mobile/rails/version.rb",
    "vendor/assets/javascripts/jquery.mobile.js",
    "vendor/assets/javascripts/jquery.mobile.min.js",
    "vendor/assets/stylesheets/jquery.mobile.css",
    "vendor/assets/stylesheets/jquery.mobile.min.css"
  ]
  s.homepage = %q{http://github.com/mjbellantoni/jquery-mobile-rails}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{This gem provides jQuery Mobile for your Rails 3.1 application.}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<jquery-rails>, ["= 1.0.13"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
    else
      s.add_dependency(%q<jquery-rails>, ["= 1.0.13"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    end
  else
    s.add_dependency(%q<jquery-rails>, ["= 1.0.13"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
  end
end

